import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
		<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
			<div className="min-h-screen flex flex-col bg-gray-50 text-gray-900 font-sans">
				<NavBar />


				{/* Main Content */}
				<main className="flex-1 p-6 md:px-8 max-w-[1600px] w-full mx-auto">
					{children}
				</main>
				</div>
		</body>
    </html>
  );
}
